sudo: required
services:
    - docker

before_install:
    - docker build -t devdocker -f Dockerfile.dev .

script:
    - docker run -e CI=true devdocker npm run-script test 

deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAUABX444ULEO4L5UC
  secret_access_key:
    secure: "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"
  region: "us-east-2"
  app: "react-container"
  env: "Reactcontainer-env"
  bucket_name: "elasticbeanstalk-us-east-2-274995144488"
  bucket_path: "react-container"
  
  on:
    branch: main


